# Generated by Django 4.0.5 on 2022-06-08 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField(max_length=300)),
                ('quantity_now', models.IntegerField()),
                ('book_cover', models.ImageField(default='book.jpg', upload_to='')),
                ('original_quantity', models.IntegerField()),
                ('db_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
