# Generated by Django 4.0.5 on 2022-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_db_updated_book_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='BookStore/book/media/book.jpg', upload_to=''),
        ),
    ]
