# Generated by Django 4.0.5 on 2022-06-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='', upload_to='book/images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='db_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
